application: playlist-service
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: lxml
  version: latest

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: app/static/img/favicon.ico
  upload: app/static/img/favicon.ico

- url: /robots.txt
  static_files: app/static/robots.txt
  upload: app/static/robots.txt

- url: /static
  static_dir: app/static

- url: .*
  script: run.app.app
